version: "3"
services:
  api_server:
    build: .
    ports:
      - "5005:5005"
      - "38080:8080"
    restart: unless-stopped
    networks: 
      - examina_network
networks:
  examina_network:
    external: true
    driver: bridge